name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: abtinm/qmapping:artifact
    steps:
      - name: test
        uses: actions/checkout@v3
      - name: foo
        run: ls

